# Generated by Django 4.2.7 on 2023-12-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='pakiet',
            options={'verbose_name_plural': 'Pakiety'},
        ),
        migrations.AlterModelOptions(
            name='pracownik',
            options={'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='sprzet',
            options={'verbose_name_plural': 'Lista sprzętu'},
        ),
        migrations.AlterModelOptions(
            name='utarg',
            options={'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='wypozyczenie',
            options={'verbose_name_plural': 'Wypożyczenia'},
        ),
        migrations.RenameField(
            model_name='klient',
            old_name='Imie',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='klient',
            old_name='Kod_pocztowy',
            new_name='kod_pocztowy',
        ),
        migrations.RenameField(
            model_name='klient',
            old_name='Miasto',
            new_name='miasto',
        ),
        migrations.RenameField(
            model_name='klient',
            old_name='Nazwisko',
            new_name='nazwisko',
        ),
        migrations.RenameField(
            model_name='klient',
            old_name='Nr_telefonu',
            new_name='nr_telefonu',
        ),
        migrations.RenameField(
            model_name='klient',
            old_name='Ulica_nrDomu',
            new_name='ulica_nrDomu',
        ),
        migrations.RenameField(
            model_name='pracownik',
            old_name='Imie',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='pracownik',
            old_name='Nazwisko',
            new_name='nazwisko',
        ),
        migrations.RenameField(
            model_name='sprzet',
            old_name='Cena',
            new_name='cena',
        ),
        migrations.RenameField(
            model_name='sprzet',
            old_name='Dlugosc',
            new_name='dlugosc',
        ),
        migrations.RenameField(
            model_name='sprzet',
            old_name='Marka',
            new_name='marka',
        ),
        migrations.RenameField(
            model_name='sprzet',
            old_name='Rodzaj',
            new_name='rodzaj',
        ),
        migrations.RenameField(
            model_name='sprzet',
            old_name='Stan',
            new_name='stan',
        ),
        migrations.RenameField(
            model_name='utarg',
            old_name='Data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='utarg',
            old_name='Kwota',
            new_name='kwota',
        ),
        migrations.RenameField(
            model_name='wypozyczenie',
            old_name='Do',
            new_name='do',
        ),
        migrations.RenameField(
            model_name='wypozyczenie',
            old_name='Od',
            new_name='od',
        ),
        migrations.RenameField(
            model_name='wypozyczenie',
            old_name='Zaplacone',
            new_name='zaplacone',
        ),
    ]
