# Generated by Django 4.2.7 on 2023-12-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_sprzet_rodzaj_alter_sprzet_stan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'ordering': ('kategoria',), 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='stan',
            options={'ordering': ('stan',), 'verbose_name_plural': 'Stany'},
        ),
        migrations.AlterModelOptions(
            name='utarg',
            options={'ordering': ('data',), 'verbose_name_plural': 'Utarg'},
        ),
    ]
