# Generated by Django 4.2.7 on 2023-12-25 18:41

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_wypozyczenie_pracownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='PESEL',
            field=models.CharField(max_length=11, unique=True, validators=[item.models.PESEL_validation]),
        ),
        migrations.AlterField(
            model_name='klient',
            name='kod_pocztowy',
            field=models.CharField(max_length=6, validators=[item.models.KOD_validation]),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nr_telefonu',
            field=models.CharField(max_length=9, unique=True, validators=[item.models.TEL_validation]),
        ),
    ]
