# Generated by Django 4.2.7 on 2023-12-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_klient_pesel_alter_klient_kod_pocztowy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=3)),
            ],
        ),
    ]
