# Generated by Django 4.2.7 on 2023-12-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_bool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bool',
            options={'ordering': ('TYPE',), 'verbose_name_plural': 'Typy'},
        ),
    ]
