# Generated by Django 4.2.7 on 2024-01-09 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0013_alter_wypozyczenie_zaplacone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='wypozyczone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.bool'),
        ),
        migrations.AlterField(
            model_name='wypozyczenie',
            name='klient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='item.klient'),
        ),
        migrations.AlterField(
            model_name='wypozyczenie',
            name='pracownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
